### PR TITLE
Bump datasets package

### PR DESCRIPTION
**Pull request by shubhobm**
The detector in `packagehallucination` is erroring out:
```
  File "/home/ec2-user/anaconda3/envs/py3.11/lib/python3.11/site-packages/garak/detectors/packagehallucination.py", line 52, in detect
    self._load_package_list()
  File "/home/ec2-user/anaconda3/envs/py3.11/lib/python3.11/site-packages/garak/detectors/packagehallucination.py", line 44, in _load_package_list
    pypi_dataset = datasets.load_dataset(self.pypi_dataset_name, split="train")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/py3.11/lib/python3.11/site-packages/datasets/load.py", line 2146, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/py3.11/lib/python3.11/site-packages/datasets/builder.py", line 1173, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
```

Turns out this is due to a [breaking change in `fsspec`](https://github.com/huggingface/datasets/issues/6352), which is propagating to garak through the `datasets` dependency.

Solution is to bump `datasets`.

### CODE REVIEW

**Comment by leondz** [comment]
Can you sync up requirements.txt to this? The tests should pick it up (`python3 -m pytest tests/test_reqs.py`). Wrote a local fix then realised I don't have access to your branch

**Review by leondz — CHANGES_REQUESTED** [review]
also bump requirements.txt datasets ver

**Comment by leondz** [comment]
Looks like [it recently broke again](https://github.com/huggingface/datasets/issues/6352#issuecomment-1961328876) and the current magic version spec is
```
datasets>=2.14.6,<2.17
```

**Comment by shubhobm** [comment]
Updated versions in both places.

**Review by leondz — APPROVED** [review]

**Pull request merged**
