### PR TITLE
Support Nested Json API Responses

### PR DESCRIPTION
**Pull request by au70ma70n**

### CODE REVIEW

**Comment by au70ma70n** [comment]
I have read the DCO Document and I hereby sign the DCO

**Comment by jmartin-tech** [comment]
@au70ma70n can you update the description here to explain what the goal is here and why it would be a default functionality?

Can you provided some examples of configuration and responses both impacted and not impacted by this revision?

If I am understanding this correctly the need here is to extract a value in the result as the `response_json_field` that is not at the top level of the parsed response.

Thinking on this would there be value in enabling `response_json_field` to be a [JSONPath](https://pypi.org/project/jsonpath-ng/) query?

**Comment by leondz** [comment]
Is this related to #487 ?

**Comment by leondz** [comment]
@au70ma70n Thanks very much for this. We'll cue up a general fix for the next few days.

**Comment by leondz** [comment]
tracking general fix in #651

**Comment by leondz** [comment]
flexible fix provided in #651 (now merged). thank you for pushing this along!

**Pull request closed without merging**
